theme: jekyll-theme-minimal
title: Jack the Ripper in Popular Culture
description: This website was created with the aim of presenting and connecting various manifestations of artworks connected to the infamous serial killer. 
link: [I'm an inline-style link](jacktheripper-1888.github.io/map.html)
