theme: jekyll-theme-minimal
title: Welcome!
description: This website was created with the aim of presenting and connecting various manifestations of artworks connected to the infamous serial killer. 
